---
all:
  children:
    home:
      children:
        k3s:
          vars:
            k3s_registration_address: "10.0.2.4"
          children:
            k3s_master:
              hosts:
                vm-dev-1:
                  ansible_host: 40.64.124.169
                  k3s_control_node: true
                  k3s_cluster_init: true
                  k3s_kubelet_args: ["max-pods=110"]
            k3s_workers:
              hosts:
                vm-dev-2:
                  ansible_host: 20.125.60.249
                  k3s_control_node: false
                  k3s_kubelet_args: ["max-pods=45"]
      vars:
        ansible_become: yes
        ansible_port: 22
        ansible_user: adminuser
        ansible_ssh_private_key_file: ~/.ssh/azure_ssh_key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

        env: home
